# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroquest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='armor',
        ),
        migrations.AlterField(
            model_name='player',
            name='spell',
            field=models.ManyToManyField(related_name='spells', to='armery.Spell', verbose_name='Hechizos'),
        ),
    ]
