# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armery', '0003_armor_others'),
        ('heroquest', '0002_auto_20160819_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='armery.Armor', verbose_name='Armaduras'),
        ),
        migrations.AddField(
            model_name='player',
            name='others',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='armery.Others', verbose_name='Otros'),
        ),
    ]
