# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroquest', '0003_auto_20160819_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='armery.Armor', verbose_name='Armaduras'),
        ),
        migrations.AlterField(
            model_name='player',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='armery.Others', verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='armery.Weapon', verbose_name='Armas'),
        ),
    ]
