# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroquest', '0004_auto_20160819_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='adventures',
            field=models.ManyToManyField(blank=True, null=True, related_name='adventures', to='heroquest.Adventure', verbose_name='Participo en las Aventuras'),
        ),
    ]
