# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapon', verbose_name='Imágen')),
                ('type', models.IntegerField(choices=[(1, 'Agua'), (2, 'Fuego'), (3, 'Aire'), (4, 'Tierra')], verbose_name='Tipo de Magia')),
            ],
            options={
                'verbose_name': 'Hechizo',
                'verbose_name_plural': 'Hechizos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapon', verbose_name='Imágen')),
                ('cost', models.IntegerField(verbose_name='Costo')),
                ('magic_equipment', models.BooleanField(default=False, verbose_name='Equipo Magico')),
                ('special', models.BooleanField(default=False, verbose_name='Arma Especial')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armery.Weapon')),
            ],
            options={
                'verbose_name': 'Armadura',
                'verbose_name_plural': 'Armaduras',
                'ordering': ('name',),
            },
            bases=('armery.weapon',),
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armery.Weapon')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ('name',),
            },
            bases=('armery.weapon',),
        ),
    ]
