# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroquest', '0002_auto_20160819_1747'),
        ('armery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='weapon_ptr',
        ),
        migrations.RemoveField(
            model_name='others',
            name='weapon_ptr',
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
    ]
