# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armery', '0002_auto_20160819_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapon', verbose_name='Imágen')),
                ('cost', models.IntegerField(verbose_name='Costo')),
                ('magic_equipment', models.BooleanField(default=False, verbose_name='Equipo Magico')),
                ('special', models.BooleanField(default=False, verbose_name='Arma Especial')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Armaduras',
                'verbose_name': 'Armadura',
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapon', verbose_name='Imágen')),
                ('cost', models.IntegerField(verbose_name='Costo')),
                ('magic_equipment', models.BooleanField(default=False, verbose_name='Equipo Magico')),
                ('special', models.BooleanField(default=False, verbose_name='Arma Especial')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Otros',
                'verbose_name': 'Otro',
            },
        ),
    ]
